version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: ship-management-mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: ship_management
      MYSQL_USER: shipuser
      MYSQL_PASSWORD: shippassword
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - ship-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  ship-network:
    driver: bridge

volumes:
  mysql-data:
